# pytest.ini
[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -ra
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')